import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/common/navbar";
import Providers from "../queryclient";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { SidebarProvider } from "@/components/ui/sidebar";
import { SettingsSidebar } from "../../components/common/sidebar";
import { Toaster } from "@/components/ui/sonner";
import { Suspense } from "react";
import ClientProvider from "../../components/provider/clientProvider";
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-screen w-full  m-0 antialiased">
        <Providers>
          <NuqsAdapter>
            {/* SidebarProvider bao bọc toàn bộ màn hình */}
            <SidebarProvider className="h-full w-full flex">
              {/* 1. Sidebar nằm cố định bên trái, chiếm trọn chiều cao màn hình */}
              <Suspense fallback={null}>
                <SettingsSidebar />
              </Suspense>
              {/* 2. Cột bên phải chứa Navbar ở tnpm rên và Nội dung ở dưới */}
              <div className="flex-1 flex flex-col min-w-0 ">
                <Suspense fallback={null}>
                  <Navbar />
                </Suspense>

                {/* Vùng hiển thị nội dung chính của các trang (profile, language,...) */}
                <ClientProvider>
                  <main>{children}</main>
                </ClientProvider>
                <Toaster richColors position="top-right" />
              </div>
            </SidebarProvider>
          </NuqsAdapter>
        </Providers>
      </body>
    </html>
  );
}
