import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
import { Suspense } from "react";

import Navbar from "@/components/common/navbar";
import { SettingsSidebar } from "@/components/common/sidebar";
import ClientProvider from "@/components/provider/clientProvider";
import { SidebarProvider } from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/sonner";

import Providers from "../../queryclient";
import { NuqsAdapter } from "nuqs/adapters/next/app";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ShopLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="vi"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-screen w-full m-0 antialiased">
        <Providers>
          <NuqsAdapter>
            <SidebarProvider className="flex h-full w-full">
              <Suspense fallback={null}>
                <SettingsSidebar />
              </Suspense>

              <div className="flex min-w-0 flex-1 flex-col">
                <Suspense fallback={null}>
                  <Navbar />
                </Suspense>

                <ClientProvider>
                  <main>{children}</main>
                </ClientProvider>

                <Toaster richColors position="top-right" />
              </div>
            </SidebarProvider>
          </NuqsAdapter>
        </Providers>
      </body>
    </html>
  );
}
